IF OBJECT_ID(N'dbo.HiddenTest', N'U') IS NOT NULL
BEGIN
	DROP TABLE [dbo].[HiddenTest]
END
GO
CREATE TABLE [dbo].[HiddenTest](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ConceptId] [int] NOT NULL,
	[TestId] [int] NULL,
	[ComplexId] [int] NOT NULL,
 CONSTRAINT [PK_HiddenTest] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_HiddenTest_ConceptId_ComplexId] ON [dbo].[HiddenTest]
(
	[ConceptId] ASC,
	[ComplexId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



