[modules]
relative_modules_path_list = [
    "../",
    "../container",
    "../server",
    "../modules/admin",
    "../modules/complex",
    "../modules/confirmation",
    "../modules/course-projects",
    "../modules/diplom-projects",
    "../modules/editor",
    "../modules/schedule",
    "../modules/statistics",
    "../modules/subjects",
    "../modules/tests",
]

exclude_modules_for_install = []

exclude_modules_for_uninstall = []

exclude_modules_for_reinstall = []

exclude_modules_for_build = [
    '../server',
]

exclude_modules_for_rebuild = [
    '../server',
]