
pipeline {
  agent {
    docker {                     
        image 'node:14-alpine'
        args '-v /var/jenkins/caches:/var/jenkins/caches'
    }
                    
  }

  stages {

    stage('Install container') {
      steps { 
            dir('./container') {
               sh 'npm install --force' 
            }
        }
    }

    stage('Build container') {
      steps { 
            dir('./container') {
               sh 'node_modules/.bin/ng build' 
            }
        }
    }

    stage('Build modules') {
        steps {
            dir('./build') {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './build_modules.sh'
            }
        }
    }

    stage('Install server') {
      steps { 
            dir('./server') {
               sh 'npm install --force' 
            }
        }
    }
  }
}