
pipeline {
  agent {
    docker {                     
        image 'node:14-alpine'
        args '-v /var/jenkins/caches:/var/jenkins/caches'
    }
                    
  }

  stages {

    stage('Build container') {
      steps { 
            dir('./container') {
               sh '''
			          npm install --force
                npm run build
		          '''
            }
        }
    }

    stage('Build modules') {
        steps {
            dir('./build') {
                sh '''
                  chmod +x -R ${env.WORKSPACE}
                  ./jenkins_build_modules.sh
                '''
            }
        }
    }

    stage('Install server') {
      steps { 
            dir('./server') {
              sh '''
                ls -ls
                cp * d:/CatsProject/server
              '''
            }
        }
    }
  }
}